Revert "TypeError: make_animation.<locals>.normalize_kp() got an unexpected keyword argument 'kp_source'"
This reverts commit 1b5055ec015527cc10c9b098e7da500fc498868a.